
development:
  adapter: postgresql
  encoding: unicode
  database: moves_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: moves_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: moves_production
  pool: 5
  username: 
  password:
